StartupEvents.registry('block', event => {
    event.create('hard_blackstone')
        .displayName('Hardened Blackstone')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

        event.create('hard_depthrock')
        .displayName('Hardened Depthrock')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .soundType('gilded_blackstone')
})