StartupEvents.registry("block", event => {
    event.create('depthrock_arcane_ore')
        .displayName('Arcane Ore')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('shiverstone_arcane_ore')
        .displayName('Arcane Ore')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('depthrock_lapis_ore')
        .displayName('Depthrock Lapis')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('shiverstone_lapis_ore')
        .displayName('Shiverstone Lapis')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_coal_ore')
        .displayName('Limestone Coal')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_copper_ore')
        .displayName('Limestone Copper')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_diamond_ore')
        .displayName('Limestone Diamond')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_gold_ore')
        .displayName('Limestone Gold')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_iron_ore')
        .displayName('Limestone Iron')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_mythril_ore')
        .displayName('Limestone Mythril')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_uranium_ore')
        .displayName('Limestone Uranium')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('limestone_amethyst_ore')
        .displayName('Limestone Amethyst')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('depthrock_emerald_ore')
        .displayName('Depthrock Emerald')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

    event.create('depthrock_diamond_ore')
        .displayName('Depthrock Diamond')
        .material('stone')
        .hardness(5)
        .resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .requiresTool(true)
        .soundType('gilded_blackstone')

})  